[package]
name = "alice-wm"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
bitflags = "2.13.1"
anyhow = "1.0.104"
xdg = "3.0.0"
smithay-drm-extras = { version = "0.1.0", default-features = false }

[dependencies.smithay]
version = "0.7.0"
default-features = false
features = [
    "backend_winit",
    "backend_drm",
    "backend_gbm",
    "backend_egl",
    "backend_udev",
    "backend_libinput",
    "backend_session_libseat",
    "renderer_gl",
    "renderer_multi",
    "desktop",
    "wayland_frontend",
    "xwayland",
]

[dependencies.mlua]
version = "0.12.0"
features = [
    "vendored",
    "lua55",
    "error-send",
]

